- icon: filler
  title: Fillers
  description: Over time, your face changes in many ways. This is part of the normal aging process, but genetics and environmental factors also play a role.
               Our solutions will replace volume in your lips and cheeks reducing lines and wrinkles restoring that youthful look.
- icon: botox
  title: Botox
  description: BOTOX® Cosmetic is the first and only treatment FDA-approved to temporarily make moderate to severe frown lines, crow's feet and forehead lines look better in adults. So you look like you, only with less noticeable facial lines.

- icon: lotion
  title: Rejuvenation
  description: Enhance your appearance with skin rejuvenation, resurfacing and tightening.  You can improve the appearance of your skin with the use of laser, light and other energy-based treatments, chemical peels and/or other non-ablative methods.  The result is a smoother, clearer and more youthful appearance to your skin.

- icon: hair-removal
  title: Hair Removal
  description: Lasers can selectively target a pigmented hair while leaving the surrounding skin undamaged. Each dime sized pulse of laser energy takes a fraction of a second and can treat many hairs at the same time. Compared with electrolysis, laser hair removal is more precise and much faster. Small areas such as the upper lip can be treated in less than a minute, while large areas (back, legs) may need up to an hour.

- icon: tattoo
  title: Tattoo Removal
  description: Lasers are the most common method of tattoo removal performed today. Tattoos consist of thousands of particles of tattoo ink suspended in the skin. The normal human immune system typically removes small foreign particles from the skin. Tattoo ink particles are too big to be removed by this system and are thus considered permanent. The use of lasers helps to break up these particles into smaller pieces that can be removed by the immune system.

- icon: makeup
  title: Permanent Makeup
  description: Permanent makeup is possible through a procedure called micropigmentation in which an organic pigment is embedded beneath the skin to add permanent color. The procedure involves the use of a hand-held device that punctures the skin hundreds of times per minute with a very thin needle and pushes the pigment into the desired location.

- icon: eyelashes
  title: Eyelashes
  description: Are your eyelashes thinning as you get older? Our treatment for hypotrichosis (inadequate or not enough lashes) to grow eyelashes longer, fuller and darker. The treatment more than doubles lash fullness in 16 weeks.

- icon: information
  title: Specialties
  description: We have solutions to bring out your confidence.
